#!/bin/sh

###############################################################################
#                                                                             #
# When GAMMA is used under both Windows and Unix operating systems problems   #
# with the build may arise due to "DOS" linefeeds which differ from Unix      #
# linefeeds. This can occur when GAMMA is built under Windows using typical   #
# configuration/make procedure (as will be done with CygWin & GCC). When a    #
# subsequent build is done on a Unix platform - using the same directory      #
# structure - some of the configuration and Makefiles will be corrupted by    #
# ^Ms, the DOS linefeed. The Unix configuration/build will then fail. This    #
# script will attempt to correct all necessary files by replacing the ^M      #
# characters with Unix returns. A few details:                                #
#                                                                             #
# 1.) This script, DOSNoMore, should ONLY BE RUN ON UNIX systems. The build   #
#     and installation under Windows/Cygwin can handle both the ^Ms and Unix  #
#     returns just fine. There there is no need to ever run the script from a #
#     CygWin shell under Windows (shouldn't hurt anything though).            #
# 2.) The script will clean the configuration files in this directory as well #
#     as the Makefiles in the make subdirectory. It does not recurse into the #
#     source code subdirectories to clean any makefiles therein.              #
# 3.) The GAMMA makefile is supposed to strip ^Ms when it creates a source    #
#     distribution (as of version 4.0.5). That should make use of this rare?  #
# 4.) I have written the script to run in two different ways.  The direct way #
#     uses "cat", "sed" and "|", all standard Unix commands. It is default.   #
#     An alternative means (not in use but still in this script) uses the     #
#     non-standard (but well known) program dos2unix. Since dos2unix programs #
#     differ in functionality on Unix & Windoze systems I don't like to use   #
#     it anymore. If it is used, dos2unxi must be on the Unix system & in     #
#     in the users the path. I just wouldn't run it at all on Windows/Cygwin. #
#                                                                             #
###############################################################################

#              Fix The Configuration Files In This Directory

cat configure | sed "s/^M\{1,\}$//" | sed "$ s/^Z//" >  configureU
mv -f configureU configure
chmod u+x configure

cat config.guess | sed "s/^M\{1,\}$//" | sed "$ s/^Z//" >  config.guessU
mv -f config.guessU config.guess
chmod a-x config.guess

cat config.guess | sed "s/^M\{1,\}$//" | sed "$ s/^Z//" >  config.guessU
mv -f config.guessU config.guess
chmod a-x config.guess

cat config.sub | sed "s/^M\{1,\}$//" | sed "$ s/^Z//" >  config.subU
mv -f config.subU config.sub
chmod a-x config.sub

cat config.cache | sed "s/^M\{1,\}$//" | sed "$ s/^Z//" >  config.cacheU
mv -f config.cacheU config.cache
chmod a-x config.cache

cat Makefile.in | sed "s/^M\{1,\}$//" | sed "$ s/^Z//" >  Makefile.inU
mv -f Makefile.inU Makefile.in
chmod a-x Makefile.in

cat Makefile | sed "s/^M\{1,\}$//" | sed "$ s/^Z//" >  MakefileU
mv -f MakefileU Makefile
chmod a-x Makefile

cat gamma.in | sed "s/^M\{1,\}$//" | sed "$ s/^Z//" >  gamma.inU
mv -f gamma.inU gamma.in
chmod a-x gamma.in

cat gamma | sed "s/^M\{1,\}$//" | sed "$ s/^Z//" >  gammaU
mv -f gammaU gamma
chmod a-x gamma


#           Fix The Makefiles In The Make Subdirectory

cat make/MakeBin | sed "s/^M\{1,\}$//" | sed "$ s/^Z//" > make/MakeBinU
mv -f make/MakeBinU make/MakeBin
chmod a-x make/MakeBin

cat make/MakeBuild | sed "s/^M\{1,\}$//" | sed "$ s/^Z//" > make/MakeBuildU
mv -f make/MakeBuildU make/MakeBuild
chmod a-x make/MakeBuild

cat make/MakeDefs | sed "s/^M\{1,\}$//" | sed "$ s/^Z//" > make/MakeDefsU
mv -f make/MakeDefsU make/MakeDefs
chmod a-x make/MakeDefs

cat make/MakeDemo | sed "s/^M\{1,\}$//" | sed "$ s/^Z//" > make/MakeDemoU
mv -f make/MakeDemoU make/MakeDemo
chmod a-x make/MakeDemo

cat make/MakeGam | sed "s/^M\{1,\}$//" | sed "$ s/^Z//" > make/MakeGamU
mv -f make/MakeGamU make/MakeGam
chmod a-x make/MakeGam

cat make/MakeGen | sed "s/^M\{1,\}$//" | sed "$ s/^Z//" > make/MakeGenU
mv -f make/MakeGenU make/MakeGen
chmod a-x make/MakeGen

cat make/MakeGen.in | sed "s/^M\{1,\}$//" | sed "$ s/^Z//" > make/MakeGen.inU
mv -f make/MakeGen.inU make/MakeGen.in
chmod a-x make/MakeGen.in

cat make/MakeModBin | sed "s/^M\{1,\}$//" | sed "$ s/^Z//" > make/MakeModBinU
mv -f make/MakeModBinU make/MakeModBin
chmod a-x make/MakeModBin

cat make/MakeModBin.in | sed "s/^M\{1,\}$//" | sed "$ s/^Z//" > make/MakeModBin.inU
mv -f make/MakeModBin.inU make/MakeModBin.in
chmod a-x make/MakeModBin.in

cat make/MakeModBuild | sed "s/^M\{1,\}$//" | sed "$ s/^Z//" > make/MakeModBuildU
mv -f make/MakeModBuildU make/MakeModBuild
chmod a-x make/MakeModBuild

cat make/MakeModFiles | sed "s/^M\{1,\}$//" | sed "$ s/^Z//" > make/MakeModFilesU
mv -f make/MakeModFilesU make/MakeModFiles
chmod a-x make/MakeModFiles

cat make/MakeModGen | sed "s/^M\{1,\}$//" | sed "$ s/^Z//" > make/MakeModGenU
mv -f make/MakeModGenU make/MakeModGen
chmod a-x make/MakeModGen

cat make/MakeModGen.in | sed "s/^M\{1,\}$//" | sed "$ s/^Z//" > make/MakeModGen.inU
mv -f make/MakeModGen.inU make/MakeModGen.in
chmod a-x make/MakeModGen.in

cat make/MakeMods | sed "s/^M\{1,\}$//" | sed "$ s/^Z//" > make/MakeModsU
mv -f make/MakeModsU make/MakeMods
chmod a-x make/MakeMods

cat make/MakeModSrc | sed "s/^M\{1,\}$//" | sed "$ s/^Z//" > make/MakeModSrcU
mv -f make/MakeModSrcU make/MakeModSrc
chmod a-x make/MakeModSrc

cat make/MakeModSrcBP | sed "s/^M\{1,\}$//" | sed "$ s/^Z//" > make/MakeModSrcBPU
mv -f make/MakeModSrcBPU make/MakeModSrcBP
chmod a-x make/MakeModSrcBP

cat make/MakeModTarg | sed "s/^M\{1,\}$//" | sed "$ s/^Z//" > make/MakeModTargU
mv -f make/MakeModTargU make/MakeModTarg
chmod a-x make/MakeModTarg

cat make/MakeModTest | sed "s/^M\{1,\}$//" | sed "$ s/^Z//" > make/MakeModTestU
mv -f make/MakeModTestU make/MakeModTest
chmod a-x make/MakeModTest

cat make/MakeModTestBP | sed "s/^M\{1,\}$//" | sed "$ s/^Z//" > make/MakeModTestBPU
mv -f make/MakeModTestBPU make/MakeModTestBP
chmod a-x make/MakeModTestBP

cat make/MakeModVars | sed "s/^M\{1,\}$//" | sed "$ s/^Z//" > make/MakeModVarsU
mv -f make/MakeModVarsU make/MakeModVars
chmod a-x make/MakeModVars

cat make/MakeMSVC | sed "s/^M\{1,\}$//" | sed "$ s/^Z//" > make/MakeMSVCU
mv -f make/MakeMSVCU make/MakeMSVC
chmod a-x make/MakeMSVC

cat make/MakeSrc | sed "s/^M\{1,\}$//" | sed "$ s/^Z//" > make/MakeSrcU
mv -f make/MakeSrcU make/MakeSrc
chmod a-x make/MakeSrc

cat make/MakeTargs | sed "s/^M\{1,\}$//" | sed "$ s/^Z//" > make/MakeTargsU
mv -f make/MakeTargsU make/MakeTargs
chmod a-x make/MakeTargs

cat make/MakeTest | sed "s/^M\{1,\}$//" | sed "$ s/^Z//" > make/MakeTestU
mv -f make/MakeTestU make/MakeTest
chmod a-x make/MakeTest

cat make/MakeVars | sed "s/^M\{1,\}$//" | sed "$ s/^Z//" > make/MakeVarsU
mv -f make/MakeVarsU make/MakeVars
chmod a-x make/MakeVars


###############################################################################
###############################################################################
###############################################################################
#                                                                             #
# These are dos2unix Commands That Do Try To Do The Same Thing. Only Works    #
# Well On Unix Systems.... NOT On Cygwin With The dos2unix Programs I've Seen #
#                                                                             #
###############################################################################
###############################################################################
###############################################################################

#              Fix The Configuration Files In This Directory

#dos2unix configure > configureU
#mv -f configureU configure
#chmod u+x configure
#
#dos2unix config.guess > config.guessU
#mv -f config.guessU config.guess
#chmod a-x config.guess
#
#dos2unix config.guess > config.guessU
#mv -f config.guessU config.guess
#chmod a-x config.guess
#
#dos2unix config.sub > config.subU
#mv -f config.subU config.sub
#chmod a-x config.sub
#
#dos2unix config.cache > config.cacheU
#mv -f config.cacheU config.cache
#chmod a-x config.cache
#
#dos2unix Makefile.in > Makefile.inU
#mv -f Makefile.inU Makefile.in
#chmod a-x Makefile.in
#
#dos2unix Makefile > MakefileU
#mv -f MakefileU Makefile
#chmod a-x Makefile
#
#dos2unix gamma.in > gamma.inU
#mv -f gamma.inU gamma.in
#chmod a-x gamma.in
#
#dos2unix gamma > gammaU
#mv -f gammaU gamma
#chmod a-x gamma

#           Fix The Makefiles In The Make Subdirectory

#dos2unix make/MakeMods > make/MakeModsU
#mv -f make/MakeModsU make/MakeMods
#chmod a-x make/MakeMods
#
#dos2unix make/MakeGen > make/MakeGenU
#mv -f make/MakeGenU make/MakeGen
#chmod a-x make/MakeGen
#
#dos2unix make/MakeGam > make/MakeGamU
#mv -f make/MakeGamU make/MakeGam
#chmod a-x make/MakeGam
#
#dos2unix make/MakeTargs > make/MakeTargsU
#mv -f make/MakeTargsU make/MakeTargs
#chmod a-x make/MakeTargs
#
#dos2unix make/MakeBuild > make/MakeBuildU
#mv -f make/MakeBuildU make/MakeBuild
#chmod a-x make/MakeBuild
#
#dos2unix make/MakeDemo > make/MakeDemoU
#mv -f make/MakeDemoU make/MakeDemo
#chmod a-x make/MakeDemo
#
#dos2unix make/MakeTest > make/MakeTestU
#mv -f make/MakeTestU make/MakeTest
#chmod a-x make/MakeTest
#
#dos2unix make/MakeSrc > make/MakeSrcU
#mv -f make/MakeSrcU make/MakeSrc
#chmod a-x make/MakeSrc
#
#dos2unix make/MakeBin > make/MakeBinU
#mv -f make/MakeBinU make/MakeBin
#chmod a-x make/MakeBin
#
#dos2unix make/MakeMSVC > make/MakeMSVCU
#mv -f make/MakeMSVCU make/MakeMSVC
#chmod a-x make/MakeMSVC
#
#dos2unix make/MakeVars > make/MakeVarsU
#mv -f make/MakeVarsU make/MakeVars
#chmod a-x make/MakeVars
