
%include "PulWaveform.i"
%include "PulComposite.i"
%include "Pulse.i"
%include "PulGauss.i"
%include "PulSinc.i"
%include "PulCycle.i"
%include "PulMLEV.i"
%include "PulTrain.i"
%include "PulSupCycle.i"
