#!/bin/sh

cd Basics
./clean
cd ..
cd Bloch
./clean
cd ..
cd Deprecated
./clean
cd ..
cd ESRLib
./clean
cd ..
cd Floquet
./clean
cd ..
cd GamIO
./clean
cd ..
cd Gradients
./clean
cd ..
cd HSLib
./clean
cd ..
cd IntRank2
./clean
cd ..
cd LSLib
./clean
cd ..
cd Level1
./clean
cd ..
cd Level2
./clean
cd ..
cd Matrix
./clean
cd ..
cd MultiSys
./clean
cd ..
cd Pulses
./clean
cd ..
cd Solids
./clean
cd ..
cd Testing
./clean
cd ..
cd WBR
./clean
cd ..



